Minor corrections in Hot Code Replacement
This commit provides corrections after the code review.

A class and an object used as messages when reenabling breakpoints are
described and placed in proper companion objects.

ChangedClassFilesVisitor can't be reused anymore but we got rid of var
and `reset` method.

In case of error we use eclipseLog so users will be aware that
something went wrong. I find it quite informative, when I see that
redefining classes failed e.g. because of:
java.lang.UnsupportedOperationException: Add method not implemented
at org.eclipse.jdi.internal.VirtualMachineImpl.redefineClasses(VirtualMachineImpl.java:1245)
(...)
There's also used EclipseUtils.withSafeRunner when it's possible.

Also corrected comments and logged messages (inter alia they are more
consistent with other error messages which we have in Scala IDE).