Fixed nightly builds.
Allow me to elaborate on the reason of the failure:

The key element is the ``ColourPreferenceInitializer``, which is eagerly
intialized by Eclipse through the extension point:
``org.eclipse.core.runtime.preferences``, declared in the plugin.xml.
The initialization of ``ColourPreferenceInitializer`` results in a call
to ``ColourPreferenceInitializer.initializeDefaultPreferences``, whose implementation
currently depends on UI classes belonging to ``org.eclipse.jdt.ui`` bundle.

This caused some tests to fail in our CI server because the session executing the tests
on that machine does not have access to display components.

The resulting stacktrace was something on the line of the line of:

```
java.lang.NoClassDefFoundError: org/eclipse/jdt/internal/ui/javaeditor/DocumentAdapter
[...]
Caused by: org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter$TerminatingClassNotFoundException: An error occurred while automatically activating bundle org.eclipse.jdt.ui (45).
[...]
Caused by: java.lang.NullPointerException
	at org.eclipse.jface.resource.FontRegistry.calculateDefaultFont(FontRegistry.java:519)
	at org.eclipse.jface.resource.FontRegistry.defaultFontRecord(FontRegistry.java:562)
	at org.eclipse.jface.resource.FontRegistry.defaultFontData(FontRegistry.java:575)
	at org.eclipse.jface.resource.FontRegistry.getFontData(FontRegistry.java:591)
	at org.eclipse.jdt.internal.ui.JavaPlugin.ensurePreferenceStoreBackwardsCompatibility(JavaPlugin.java:448)
```

The actual fix is pretty stupid: the implementation of ``ColourPreferenceInitializer.initializeDefaultPreferences``
is now executed only if ``headlessMode`` is disabled.